//
//  MainPageWorker.swift
//  NerverSitUpTest
//
//  Created by Ratchanon Insuvanno on 6/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation
import Moya
import Alamofire
class MainPageWorker {
    // MARK: Worker    
    func getCoins(completion: @escaping (Result<GetCoinsViewModel,ErrorViewModel>) -> Void) {
        let coinServiceProvider = MoyaProvider<CoinDeskService>()
        coinServiceProvider.request(.getCoins) { result in
            switch result {
            case .success(let value):
                let decoder = JSONDecoder()
                let response = try! decoder.decode(GetCoinsViewModel.self, from: value.data)
                completion(.success(response))
            case .failure(let error):
                let decoder = JSONDecoder()
                let response = try? decoder.decode(ErrorViewModel.self, from: error.response?.data ?? Data())
                completion(.failure(.init(status: response?.status, code: response?.code, message: response?.message)))
            }
        }
    }

    
}



