//
//  MainPageInteractor.swift
//  NerverSitUpTest
//
//  Created by Ratchanon Insuvanno on 6/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire


import UIKit

protocol MainPageBusinessLogic {
    func callGetCoins()
}


class MainPageInteractor: MainPageBusinessLogic
{
    var presenter: MainPagePresentationLogic?
    var worker: MainPageWorker = MainPageWorker()

    func callGetCoins() {
        worker.getCoins(completion: { result in
            let response = MainPage.FetchCoin.Response(result: result)
            self.presenter?.presentGetCoin(response: response)
        })
    }
    
}
