//
//  MainPageModels.swift
//  NerverSitUpTest
//
//  Created by Ratchanon Insuvanno on 6/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainPage
{
  // MARK: Use cases
  
    enum FetchCoin
      {
        struct Request {
        }
        struct Response {
             var result: Result<GetCoinsViewModel, ErrorViewModel>
        }
        struct ViewModel {
          var result: GetCoinsViewModel?
          var errorResult : ErrorViewModel?
        }
      }
}
