//
//  MainPagePresenter.swift
//  NerverSitUpTest
//
//  Created by Ratchanon Insuvanno on 6/1/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPagePresentationLogic
{
    func presentGetCoin(response: MainPage.FetchCoin.Response)
}

class MainPagePresenter: MainPagePresentationLogic
{
    weak var viewController: MainPageDisplayLogic?

    
    func presentGetCoin(response: MainPage.FetchCoin.Response) {
        switch response.result {
        case .success(let value):
            viewController?.displayGetCoinSucess(viewModel: MainPage.FetchCoin.ViewModel(result: value, errorResult: nil))
        case .failure(let value):
            viewController?.displayGetCoinFailure(viewModel: MainPage.FetchCoin.ViewModel(result: nil, errorResult: value))
        }
    }
}
